service: telephonist-fsharp
provider:
  name: aws
  profile: private
  region: eu-central-1
  stage: production
  runtime: dotnetcore1.0
package:
  artifact: bin/release/netcoreapp1.0/deploy-package.zip
functions:
  TestOnCallPhoneNumber:
    handler: TelephonistServiceFSharp::Telephonist.DialingAPI::testOnCallPhoneNumber
    environment:
      TWILIO_ACCOUNT_SID: ${file(.local-keys.yml):TWILIO_ACCOUNT_SID}
      TWILIO_API_TOKEN: ${file(.local-keys.yml):TWILIO_API_TOKEN}
      CALLER: ${file(.local-keys.yml):CALLER}
      ON_CALL_NUMBER: ${file(.local-keys.yml):ON_CALL_NUMBER}
      TEST_SCENARIO_TWIML_URL: ${file(.local-keys.yml):TEST_SCENARIO_TWIML_URL}
    events:
      - http:
          path: calls/test
          method: post
          integration: lambda
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:${self:provider.region}:${file(.local-keys.yml):AWS_ACCOUNT_ID}:userpool/${file(.local-keys.yml):COGNITO_USER_POOL_NAME}"
          statusCodes:
            200:
              pattern: ''
